
package calculadoraais;

// Autores: David Sánchez Dueñas y Sergio Lázaro Matesanz
public class Calculadora extends javax.swing.JFrame {
    int contador = 0;   //Comprueba que hay el mismo numero de parentesis abiertos que de cerrados
    int veces = 0;      //Comprueba cuantas veces se ha dado al igual
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        
        //Se desahibilitan de inicio los botones que escriban una expresion erronea
        
        Boton_Igual.setEnabled(false);
        Boton_CerrarParentesis.setEnabled(false);
        Boton_Division.setEnabled(false);
        Boton_Igual.setEnabled(false);
        Boton_Multiplicacion.setEnabled(false);
        Boton_Suma.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoPantalla = new javax.swing.JTextField();
        Boton_4 = new javax.swing.JButton();
        Boton_7 = new javax.swing.JButton();
        Boton_1 = new javax.swing.JButton();
        Boton_8 = new javax.swing.JButton();
        Boton_2 = new javax.swing.JButton();
        Boton_5 = new javax.swing.JButton();
        Boton_9 = new javax.swing.JButton();
        Boton_0 = new javax.swing.JButton();
        Boton_6 = new javax.swing.JButton();
        Boton_3 = new javax.swing.JButton();
        Boton_Igual = new javax.swing.JButton();
        Boton_Suma = new javax.swing.JButton();
        Boton_Multiplicacion = new javax.swing.JButton();
        Boton_AbrirParentesis = new javax.swing.JButton();
        Boton_Division = new javax.swing.JButton();
        Boton_Resta = new javax.swing.JButton();
        Boton_CerrarParentesis = new javax.swing.JButton();
        Boton_Decimal = new javax.swing.JButton();
        Boton_CE = new javax.swing.JButton();
        Boton_C = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextoPantalla.setEditable(false);
        TextoPantalla.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        TextoPantalla.setText("Inserte exp");
        TextoPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoPantallaActionPerformed(evt);
            }
        });

        Boton_4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_4.setText("4");
        Boton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_4ActionPerformed(evt);
            }
        });

        Boton_7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_7.setText("7");
        Boton_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_7ActionPerformed(evt);
            }
        });

        Boton_1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_1.setText("1");
        Boton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_1ActionPerformed(evt);
            }
        });

        Boton_8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_8.setText("8");
        Boton_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_8ActionPerformed(evt);
            }
        });

        Boton_2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_2.setText("2");
        Boton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_2ActionPerformed(evt);
            }
        });

        Boton_5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_5.setText("5");
        Boton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_5ActionPerformed(evt);
            }
        });

        Boton_9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_9.setText("9");
        Boton_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_9ActionPerformed(evt);
            }
        });

        Boton_0.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_0.setText("0");
        Boton_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_0ActionPerformed(evt);
            }
        });

        Boton_6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_6.setText("6");
        Boton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_6ActionPerformed(evt);
            }
        });

        Boton_3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_3.setText("3");
        Boton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_3ActionPerformed(evt);
            }
        });

        Boton_Igual.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Igual.setText("=");
        Boton_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_IgualActionPerformed(evt);
            }
        });

        Boton_Suma.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Suma.setText("+");
        Boton_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_SumaActionPerformed(evt);
            }
        });

        Boton_Multiplicacion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Multiplicacion.setText("x");
        Boton_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MultiplicacionActionPerformed(evt);
            }
        });

        Boton_AbrirParentesis.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_AbrirParentesis.setText("(");
        Boton_AbrirParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AbrirParentesisActionPerformed(evt);
            }
        });

        Boton_Division.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Division.setText("/");
        Boton_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DivisionActionPerformed(evt);
            }
        });

        Boton_Resta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Resta.setText("-");
        Boton_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RestaActionPerformed(evt);
            }
        });

        Boton_CerrarParentesis.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_CerrarParentesis.setText(")");
        Boton_CerrarParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CerrarParentesisActionPerformed(evt);
            }
        });

        Boton_Decimal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_Decimal.setText(".");
        Boton_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_DecimalActionPerformed(evt);
            }
        });

        Boton_CE.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Boton_CE.setText("CE");
        Boton_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CEActionPerformed(evt);
            }
        });

        Boton_C.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Boton_C.setText("C");
        Boton_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextoPantalla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_Igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Boton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Boton_CE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton_AbrirParentesis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Boton_CerrarParentesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Boton_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextoPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Division, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Suma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_AbrirParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton_CerrarParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Boton_0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_Decimal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Boton_C, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Boton_CE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoPantallaActionPerformed

    }//GEN-LAST:event_TextoPantallaActionPerformed

    private void Boton_7ActionPerformed(java.awt.event.ActionEvent evt) {

        //Se habilitan todos los botones al pulsar la tecla '7'
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        //reinicia el estado de todos los botones
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("7");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"7"); //Si veces = 0, se concatena el 7 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }                                       

    private void Boton_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_8ActionPerformed
        
        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("8");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"8"); //Si veces = 0, se concatena el 8 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_8ActionPerformed

    private void Boton_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_9ActionPerformed
        
        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("9");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"9"); //Si veces = 0, se concatena el 9 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_9ActionPerformed

    private void Boton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_4ActionPerformed
        
        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("4");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"4"); //Si veces = 0, se concatena el 4 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_4ActionPerformed

    private void Boton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_5ActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("5");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"5"); //Si veces = 0, se concatena el 5 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_5ActionPerformed

    private void Boton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_6ActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("6");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"6"); //Si veces = 0, se concatena el 6 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_6ActionPerformed

    private void Boton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_1ActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("1");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"1"); //Si veces = 0, se concatena el 1 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_1ActionPerformed

    private void Boton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_2ActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("2");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"2"); //Si veces = 0, se concatena el 2 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_2ActionPerformed

    private void Boton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_3ActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("3");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"3"); //Si veces = 0, se concatena el 3 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_3ActionPerformed

    private void Boton_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_0ActionPerformed
        String cadena;
        cadena = TextoPantalla.getText();
        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");      //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (veces >= 1){
            TextoPantalla.setText("0");     //Si veces >= 1, al pulsar la tecla se sobrescribe el display
            veces = 0;
        }
        else {
            TextoPantalla.setText(TextoPantalla.getText()+"0"); //Si veces = 0, se concatena el 0 con la cadena
        }
        if (contador == 0){
            Boton_CerrarParentesis.setEnabled(false);       //Si no hay parentesis abiertos, no permitir poner parentesis cerrados
        }
    }//GEN-LAST:event_Boton_0ActionPerformed

    private void Boton_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_IgualActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
                if ((!(cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') && cadena.charAt(cadena.length()-1) != ')') || (cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') && contador != 0){
                    TextoPantalla.setText("Expresion erronea"); // Si el ultimo caracter de la cadena no es un numero o un paréntesis cerrado y si el ultimo caracter de la cadena es un numero pero hay algun parentesis abierto sin cerrar , se mostrará un error por el display
                    Boton_CerrarParentesis.setEnabled(false);
                    Boton_Igual.setEnabled(false);
                    Boton_Suma.setEnabled(false);
                    Boton_Multiplicacion.setEnabled(false);
                    Boton_Division.setEnabled(false);
                    contador=0;
                }
                else{
                    //Asociación realizada por: Sergio Pérez Casquero
                    try {
                        double x = new ProyectoCalculadora().tramoParentesis(TextoPantalla.getText()); // Si el ultimo caracter de la cadena es un numero o un parentesis cerrado, se evaluará la expresión matemática
                        TextoPantalla.setText(""+x);
                        veces++;
                        contador = 0;
                        
                        
                        Boton_Igual.setEnabled(false);      //Se desactiva el boton igual, para prevenir errores
                        Boton_CerrarParentesis.setEnabled(false);
                    } 
                    catch (ExcepcionOperacionNoPermitida ex) {
                        TextoPantalla.setText(ex.getMessage());
                        if ("Operacion invalida".equals(ex.getMessage())){      //Si salta la excepcion, desactivar los botones '+','X','/',')' y '='
                            Boton_Igual.setEnabled(false);
                            Boton_CerrarParentesis.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            contador = 0;
                        }
                    }
                }
    }//GEN-LAST:event_Boton_IgualActionPerformed

    private void Boton_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DecimalActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        
        if ((cadena.length() <= 0) || ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText()))){
            TextoPantalla.setText("0.");                                //Si la cadena esta vacia o hay en ella un mensaje de informacion de la calculadora, borrará el mensaje y pondrá "0."
        }
        else if (cadena.charAt(cadena.length()-1) == '-' || (cadena.charAt(cadena.length()-1) == '+') || (cadena.charAt(cadena.length()-1) == 'X') || (cadena.charAt(cadena.length()-1) == '/') || (cadena.charAt(cadena.length()-1) == '(') || (cadena.charAt(cadena.length()-1) == ')')){
            TextoPantalla.setText(cadena+"0.");                         //Si la cadena termina en un signo de operación o un paréntesis, añadirá a la cadena "0."
        }
        else{if (cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9' ){
                TextoPantalla.setText(TextoPantalla.getText()+".");    //Si la cadena termina en un numero, pondrá un punto a continuación
            }
        }
        //Se deshabilitan los botones no compatibles con el decimal
        
        Boton_AbrirParentesis.setEnabled(false);
        Boton_CerrarParentesis.setEnabled(false);
        Boton_Decimal.setEnabled(false);
        Boton_Division.setEnabled(false);
        Boton_Igual.setEnabled(false);
        Boton_Multiplicacion.setEnabled(false);
        Boton_Resta.setEnabled(false);
        Boton_Suma.setEnabled(false);
    }//GEN-LAST:event_Boton_DecimalActionPerformed

    private void Boton_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CEActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if (cadena.length() == 1) {
            if (cadena.charAt(cadena.length()-1) == '('){                   //Si el ultimo carácter de la cadena es un parentesis, se actualizará el contador de parentesis
                contador--;
            }
            if (cadena.charAt(cadena.length()-1) == ')'){                   //Si el ultimo carácter de la cadena es un parentesis, se actualizará el contador de parentesis
                contador++;
            }
            contador = 0;
            TextoPantalla.setText("Inserte exp"); // Si la cadena solo tiene un caracter, borrará dicho carácter y solicitará una expresión matemática
            
            //Se deshabilitan los botones no compatibles con CE
            
            Boton_Igual.setEnabled(false);
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
            
        }
        
        else if (cadena.length() > 0 && !("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText()))){
            if (cadena.charAt(cadena.length()-1) == '('){                   //Si el ultimo carácter de la cadena es un parentesis, se actualizará el contador de parentesis
                contador--;
            }
            else if (cadena.charAt(cadena.length()-1) == ')'){
                contador++;
            }
            
            cadena = cadena.substring(0, cadena.length()-1);                //Si la cadena tiene mas de un caracter y no es un mensaje de informacion de la calculadora, borrará la última posición de la cadena
            TextoPantalla.setText(cadena);                                  //y comprobará cual es el nuevo último carácter y, dependiendo de que carácter sea, deshabilitará los botones incompatibles con dicho
            switch (cadena.charAt(cadena.length()-1)){                      //carácter
                case '+':   Boton_Suma.setEnabled(false);
                            Boton_Resta.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_CerrarParentesis.setEnabled(false); 
                            break;
                case '-':   
                            Boton_CerrarParentesis.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Resta.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            break;
                
                case 'X':   Boton_CerrarParentesis.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            break;
                
                case '/':   Boton_CerrarParentesis.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            break;
                
                case '(':   Boton_CerrarParentesis.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            break;
                            
                case ')':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '.':   Boton_AbrirParentesis.setEnabled(false);
                            Boton_CerrarParentesis.setEnabled(false);
                            Boton_Decimal.setEnabled(false);
                            Boton_Division.setEnabled(false);
                            Boton_Igual.setEnabled(false);
                            Boton_Multiplicacion.setEnabled(false);
                            Boton_Resta.setEnabled(false);
                            Boton_Suma.setEnabled(false);
                            break;
                case '0':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '1':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '2':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '3':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '4':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '5':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '6':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '7':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '8':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
                case '9':   if (contador == 0){
                                Boton_CerrarParentesis.setEnabled(false);
                            }
                            break;
            }
        }
        else if (cadena.length() > 0 && ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText()))){
                                                        
            //Si la cadena no está vacía pero es un mensaje de informacion de la calculadora, deshabilitará los botones incompatibles con CE
            TextoPantalla.setText("Inserte exp");
            Boton_Igual.setEnabled(false);
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
        }
    }//GEN-LAST:event_Boton_CEActionPerformed

    private void Boton_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        
        if (cadena.length() >= 0){                          //La cadena que reciba se sustituirá por el mensaje "Inserte exp" y se deshabilitarán los botones incompatibles con "C"
            cadena = "Inserte exp";
            TextoPantalla.setText(cadena);
            
            Boton_Igual.setEnabled(false);
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
            contador = 0;
            veces = 0;
        }
    }//GEN-LAST:event_Boton_CActionPerformed

    private void Boton_AbrirParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AbrirParentesisActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
       
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");                              //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (cadena.charAt(cadena.length()-1) != ',') {              //Si el último carácter de la cadena es distinto a ".", entonces concatenará "(" al final de la cadena
            TextoPantalla.setText(TextoPantalla.getText()+"(");
            contador++;
            
            //Se deshabilitan los botones incompatibles con (
            
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Igual.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
            
            veces = 0;
        }
        
    }//GEN-LAST:event_Boton_AbrirParentesisActionPerformed

    private void Boton_CerrarParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CerrarParentesisActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ((cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') || cadena.charAt(cadena.length()-1) == ')'){
            if (contador > 0){
            TextoPantalla.setText(TextoPantalla.getText()+")");                 // Si el ultimo carácter de la cadena es un numero o un paréntesis cerrado, añadirá un ")" al final de la cadena
            contador--;
            
            if (contador == 0){
                Boton_CerrarParentesis.setEnabled(false);
            }
            
            }
        }
    }//GEN-LAST:event_Boton_CerrarParentesisActionPerformed

    private void Boton_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MultiplicacionActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ((cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') || (cadena.charAt(cadena.length()-1) == ')')){
            TextoPantalla.setText(TextoPantalla.getText()+"X");                 // Si el ultimo carácter de la cadena es un numero o un paréntesis cerrado, añadirá un "X" al final de la cadena
            
            //Se deshabilitan los botones incompatibles con X
            
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Igual.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
            
            veces = 0;
        }
    }//GEN-LAST:event_Boton_MultiplicacionActionPerformed

    private void Boton_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_DivisionActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ((cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') || (cadena.charAt(cadena.length()-1) == ')')){
            TextoPantalla.setText(TextoPantalla.getText()+"/");                 // Si el ultimo carácter de la cadena es un numero o un paréntesis cerrado, añadirá un / al final de la cadena
            
            //Se deshabilitan los botones incompatibles con /
            
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Igual.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Suma.setEnabled(false);
            
            veces = 0;
        }
    }//GEN-LAST:event_Boton_DivisionActionPerformed

    private void Boton_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SumaActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ((cadena.charAt(cadena.length()-1) >= '0' && cadena.charAt(cadena.length()-1) <= '9') || (cadena.charAt(cadena.length()-1) == ')')){
            TextoPantalla.setText(TextoPantalla.getText()+"+");                 // Si el ultimo carácter de la cadena es un numero o un paréntesis cerrado, añadirá un + al final de la cadena
            
            //Se deshabilitan los botones incompatibles con +
            
            Boton_Suma.setEnabled(false);
            Boton_Resta.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Igual.setEnabled(false);
            Boton_CerrarParentesis.setEnabled(false);

            
            veces = 0;
        }
    }//GEN-LAST:event_Boton_SumaActionPerformed

    private void Boton_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RestaActionPerformed

        //Se habilitan todos los botones al pulsar la tecla
        
        Boton_AbrirParentesis.setEnabled(true);
        Boton_C.setEnabled(true);
        Boton_CE.setEnabled(true);
        Boton_CerrarParentesis.setEnabled(true);
        Boton_Decimal.setEnabled(true);
        Boton_Division.setEnabled(true);
        Boton_Igual.setEnabled(true);
        Boton_Multiplicacion.setEnabled(true);
        Boton_Resta.setEnabled(true);
        Boton_Suma.setEnabled(true);
        
        String cadena;
        cadena = TextoPantalla.getText();
        if ("Inserte exp".equals(TextoPantalla.getText()) || "Expresion erronea".equals(TextoPantalla.getText()) || "Operacion invalida".equals(TextoPantalla.getText())){
            TextoPantalla.setText("");                              //Si la pantalla esta vacia o ha habido un error, poner la pantalla en blanco
        }
        if (cadena.charAt(cadena.length()-1) != '+' && cadena.charAt(cadena.length()-1) != '-' && cadena.charAt(cadena.length()-1) != '.') {
            TextoPantalla.setText(TextoPantalla.getText()+"-");     //Si el ultimo carácter es distinto de "+", "-" y ".", concatenará "-" al final de la cadena
            
            //Se deshabitan los botones incompatibles con -
            
            Boton_CerrarParentesis.setEnabled(false);
            Boton_Division.setEnabled(false);
            Boton_Igual.setEnabled(false);
            Boton_Multiplicacion.setEnabled(false);
            Boton_Resta.setEnabled(false);
            Boton_Suma.setEnabled(false);
            
            veces = 0;
        } 
    }//GEN-LAST:event_Boton_RestaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_0;
    private javax.swing.JButton Boton_1;
    private javax.swing.JButton Boton_2;
    private javax.swing.JButton Boton_3;
    private javax.swing.JButton Boton_4;
    private javax.swing.JButton Boton_5;
    private javax.swing.JButton Boton_6;
    private javax.swing.JButton Boton_7;
    private javax.swing.JButton Boton_8;
    private javax.swing.JButton Boton_9;
    private javax.swing.JButton Boton_AbrirParentesis;
    private javax.swing.JButton Boton_C;
    private javax.swing.JButton Boton_CE;
    private javax.swing.JButton Boton_CerrarParentesis;
    private javax.swing.JButton Boton_Decimal;
    private javax.swing.JButton Boton_Division;
    private javax.swing.JButton Boton_Igual;
    private javax.swing.JButton Boton_Multiplicacion;
    private javax.swing.JButton Boton_Resta;
    private javax.swing.JButton Boton_Suma;
    private javax.swing.JTextField TextoPantalla;
    // End of variables declaration//GEN-END:variables
}
